fix: fix quiz and result detail navigation
new-idea-machine/os-lesson-delivery-system pull request #38
Opened 2023-08-31 21:33 UTC by georgekwan

## Why was this PR opened?
Create new quiz screen button from the Home screen was not navigating properly after the implementation of tab navigation
Bug has been fixed

## Brief Description
Fixed Create new quiz button navigation at the Home screen
I also fixed the quiz result detail navigation from quiz result screen

## Unrelated Changes

## UI Screenshots

## Link to Referenced Trello Cards

## Mentions

2023-09-02 00:40 UTC, amEhlee requested changes
Some dysync issues between top navigation ( hamburger ) and bottom navigation. This can be reproduced by trying to access a page on the top. Trying a different page on the bottom and then trying the same page on the top again. The screen will be stuck because it still views the original top page as the current.

2023-09-05 18:01 UTC, BRashad approved these changes
I'm not sure if I can simulate the outcome of this submission on my machine locally, but based on what I see its good to go.

2023-09-07 16:20 UTC, BRashad approved these changes

2023-09-07 18:56 UTC, amEhlee approved these changes

2023-09-07 19:37 UTC, merged